version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://your-domain.com"
    volumes:
      - /vw-data:/data
    networks:
      - vw-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./adminpage/:/etc/nginx/adminpage/
      - ./ssl:/etc/ssl:ro
      - ./nginx-data:/var/log/nginx
    networks:
      - vw-network

networks:
  vw-network:
    driver: bridge